id: A9AFE97AB
title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
type: translation
pechas:
- IF0D2702F
- I6BD2168B
- I1F19B797
- ID33B6C09
- I6995B036
- IA2AAA586
- IAF03B85A
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:28:48.672677
  last_modified_at: 2023-01-04 11:28:48.672682
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IF0D2702F/7893: 90FE
  I6BD2168B/2F43: 90FE
  I1F19B797/BA30: 90FE
  ID33B6C09/193D: 90FE
  I6995B036/C850: 90FE
  IA2AAA586/A66C: 90FE
  IAF03B85A/AD81: 90FE
